# logback-spring.yml

spring:
  profiles: default

# Define appenders
appender:
  CONSOLE:
    name: CONSOLE
    class: ch.qos.logback.core.ConsoleAppender
    encoder:
      pattern: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

  FILE:
    name: FILE
    class: ch.qos.logback.core.rolling.RollingFileAppender
    file: logs/app.log
    rollingPolicy:
      class: ch.qos.logback.core.rolling.TimeBasedRollingPolicy
      fileNamePattern: logs/app.%d{yyyy-MM-dd}.log
      maxHistory: 7
    encoder:
      pattern: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

# Set root logger level
root:
  level: INFO
  appender-ref:
    - ref: CONSOLE
    - ref: FILE

# Logger overrides for packages
logger:
  - name: org.springframework.web
    level: INFO

  - name: com.shivamaggarwal.weatherapi
    level: DEBUG

  - name: org.hibernate.SQL
    level: WARN
